name = "inkwell"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "inkwell-db"
database_id   = "b3cbacdf-7d43-4352-b4b4-d0ccf2509150"

[vars]
NEXTAUTH_URL = "https://inkwell.your-subdomain.pages.dev"

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = false
